### ISSUE TITLE
Seamonkey support

### ISSUE THREAD

**Issue by xabolcs** [glandium/about-startup#1]
Please add Seamonkey support!

With a modified `install.rdf` of v0.1.7 the output is:

<table xmlns="http://www.w3.org/1999/xhtml" id="table">
<tbody><tr><th class="string">version</th><th class="string">appBuildID</th><th>main</th><th>firstPaint</th><th>sessionRestored</th><th>createTopLevelWindow</th></tr>
</tbody><tr class="average"><td class="string">2.8a2</td><td class="string">20120108013001</td><td class="">545.00</td><td class="">8726.50</td><td class="">8886.00</td><td class="">7549.00</td></tr><tr class="current"><td class="string">2.8a2</td><td class="string">20120108013001</td><td class="">44</td><td class="">5243</td><td class="">5331</td><td class="">4681</td></tr><tr><td class="string">2.8a2</td><td class="string">20120108013001</td><td class="">1046</td><td>12210</td><td>12441</td><td>10417</td></tr></table>

**Comment by glandium** [comment]
Since you forked and added TB support, could you also do a pull request with a commit mofifying install.rdf? Thanks.

**Comment by xabolcs** [comment]
Of course I do: d7af8f6dba - modifying `install.rdf`

But, could you check the  merging commit, 012d807338 too?
I merged the two support stuff into master.

If you wouldn't like to use fork queue or cherry-picking then I will happily require a new pull for these commits.

Thank You!

**Comment by glandium** [comment]
I merged your work. Thanks.
