### ISSUE TITLE
about:startup "Invalid URL"

### ISSUE THREAD

**Issue by tonymec** [glandium/about-startup#3]
Mozilla/5.0 (X11; Linux x86_64; rv:14.0) Gecko/20120330 Firefox/14.0a1 SeaMonkey/2.11a1 ID:20120330003035

Not sure exactly when it started, maybe at some time within the last week. Currently about-startup is at version 0.1.9 and trying to install 0.1.10 gives me a doorhanger saying "About startup could not be installed because SeaMonkey cannot modify the needed file".

But that's a different bug. This bug is that when I try to browse about:startup, I get a XUL error page saying:

/!\       Invalid Address

```
     The URL is not valid and cannot be loaded.
    The provided address is not in a recognized format. Please check the location bar for mistakes and try again.

[ Try Again ]
```

**Comment by glandium** [comment]
There is unfortunately nothing that can be done on about startup end here. You need to either manually upgrade to 0.1.10 (i.e. replacing the xpi in your profile), manually remove 0.1.9 (i.e. removing the xpi in your profile), or downgrade Seamonkey to aurora or an older nightly (I hear before march 20), upgrade to 0.1.10, and then upgrade Seamonkey again.

**Comment by tonymec** [comment]
Using "Check for updates" in the addons manager (after restarting SeaMonkey with only the about:addons tab) found about-startup 0.1.10; "Update" got an error, with a "retry" option. Retrying installed the update, which cured the problem. Sorry I pulled the alarm too soon.
